Document how to create a gRPC patch file
ipdk-io/stratum-deps pull request #30
Opened 2023-10-09 22:54 UTC by ffoulkes

2023-10-10 14:46 UTC, 5abeel approved these changes
LGTM

2023-10-10 15:23 UTC, 5abeel requested changes

2023-10-10 15:23 UTC, 5abeel commented on docs/how-to-create-a-grpc-patch-file.md
> +  set_target_properties(grpc_python_plugin
This should be `grpc_cpp_plugin` and not `grpc_python_plugin`

2023-10-10 15:23 UTC, 5abeel commented on docs/how-to-create-a-grpc-patch-file.md
> +Use `diff -u` to generate a patch file.
This seems to be a problem where the cmake system stalls wondering which file to patch (the CMakeLists.txt or CMakeLists.patched file) and waits for a prompt from user.

I found that generating using a `git diff CMakeLists.txt CMakeLists.patched` results in a compact diff that does not stop for user input 

Instructions here need to be updated. Also needs the example generated file updated

2023-10-10 15:54 UTC, ffoulkes commented on docs/how-to-create-a-grpc-patch-file.md
> +Use `diff -u` to generate a patch file.
This is why we have code reviews... 😄

2023-10-10 15:54 UTC, ffoulkes commented on docs/how-to-create-a-grpc-patch-file.md
> +  set_target_properties(grpc_python_plugin
Oops! 😊

2023-10-11 15:00 UTC, 5abeel approved these changes
LGTM

2023-10-11 15:33 UTC, merged